In [31]:
from PIL import Image, ImageOps, ImageFilter
import pytesseract
import re
import os
import cv2
import numpy as np

In [27]:
def image_OCR(path):
    data = {
        'name': '',
    }
    img = Image.open(path)
    og_width, og_height = img.size
    left = 150
    top = 150
    right = og_width - 150
    bottom = 1400
    cropped = img.crop((left, top, right, bottom))
    crop_width, crop_height = cropped.size
    scaling_factor = 2
    resized = cropped.resize(
        (crop_width * scaling_factor, crop_height * scaling_factor),
        resample= Image.LANCZOS
        )
    gray = ImageOps.grayscale(resized)
    text = pytesseract.image_to_string(gray, lang='eng')
    name_re = '^[A-Za-z ]+'
    data['name'] = re.search(name_re, text).group(0)
    # print(re.search(name_re, text))
    gray.show()
    return data

def go_through_folder(filepath):
    for file in os.listdir(filepath):
        print(image_OCR(f'{filepath}/{file}'))



In [50]:
def preprocess_tiktok_screenshot(image_path, output_path="processed_image.png"):
    # Read image
    img = cv2.imread(image_path)

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Resize (optional: improves OCR accuracy)
    scale_percent = 150  # Increase size by 50%
    width = int(gray.shape[1] * scale_percent / 100)
    height = int(gray.shape[0] * scale_percent / 100)
    gray = cv2.resize(gray, (width, height), interpolation=cv2.INTER_CUBIC)

    # Apply Gaussian blur to reduce noise
    blur = cv2.GaussianBlur(gray, (3, 3), 0)

    # Adaptive thresholding (better for mixed backgrounds)
    thresh = cv2.adaptiveThreshold(
        blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 15
    )

    # Optional: Morphological operations to thicken text
    kernel = np.ones((1, 1), np.uint8)
    morph = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    # Save processed image
    cv2.imwrite(output_path, morph)
    print(f"Processed image saved at {output_path}")

    processed_img = Image.open('processed_image.png')
    og_width, og_height = processed_img.size
    left = 150
    top = 150
    right = og_width - 150
    bottom = 1400
    cropped = processed_img.crop((left, top, right, bottom))
    text = pytesseract.image_to_string(cropped, lang='eng')
    return text


In [51]:
print(preprocess_tiktok_screenshot('photos_sample/IMG_8339.JPG'))

Processed image saved at processed_image.png
Karen jal
she/her/hers

@kb_houston
439 147 #&°&#®#647.8K

Following ~~ Followers | Likes

({ )



In [41]:
path = 'photos_sample/IMG_8339.JPG'
img = cv2.imread(path)
print(img)
norm_img = np.zeros((img.size[0], img.size[1]))
img = cv2.normalize(img, norm_img, 0, 255, cv2.NORM_MINMAX)
# img.show()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 68 121 108]
  [ 58 111  98]
  [ 52 102  90]
  ...
  [242 238 233]
  [255 254 249]
  [255 254 246]]

 [[ 37  91  78]
  [ 33  87  74]
  [ 40  93  80]
  ...
  [208 204 199]
  [242 239 234]
  [255 255 248]]

 [[ 24  80  67]
  [ 17  73  60]
  [ 36  90  77]
  ...
  [166 162 157]
  [214 210 205]
  [246 244 236]]]


TypeError: 'int' object is not subscriptable

In [25]:
go_through_folder('photos_sample')

{'name': 'Karen al'}
{'name': 'HoneyBloom Company J'}
{'name': 'Tiny Cabin Montessori QO'}
{'name': 'Victoria '}
{'name': 'Brittany '}
{'name': 'Leanne '}
{'name': 'saf'}
{'name': 'Mama Nurse Tina ja'}
{'name': 'Rosa '}
{'name': 'Dr'}
{'name': 'brookeahlering al'}
{'name': 'Olivia Clark jal'}
{'name': 'Olivia '}
{'name': 'Jessie Marie al'}
{'name': 'Heather'}
{'name': 'Bex '}
{'name': 'Julia '}
{'name': 'TraciDoula'}
{'name': 'Helene MomJourney JO'}
{'name': 'Rebekah '}
{'name': 'Sacia'}
{'name': 'Alexus '}


AttributeError: 'NoneType' object has no attribute 'group'

In [91]:
print(pytesseract.image_to_string(cropped, lang='eng'))

Karen al

@kb_houston
439 1,147 647.8K
Following Followers Likes

Follow Message v

mostly my cat, sometimes my life
MI
% kbhouston32@gmail.com

(=) Showcase

Niy ) Tl

